import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import type { Vehicle } from "../types";
import { ConditionSummary } from "./ConditionSummary";

const SAMPLE_SUMMARY =
	"Average condition with cosmetic wear on high-touch surfaces. Reliable drivetrain at 47,731 km, clean title, minor scratches noted.";

function makeVehicle(overrides: Partial<Vehicle> = {}): Vehicle {
	return {
		id: "v1",
		vin: "VIN123ABCDEF4567",
		year: 2024,
		make: "Toyota",
		model: "Camry",
		trim: "SE",
		body_style: "sedan",
		exterior_color: "Silver Metallic",
		interior_color: "Ebony Black",
		engine: "2.5L I4",
		transmission: "automatic",
		drivetrain: "FWD",
		odometer_km: 47731,
		fuel_type: "gasoline",
		condition_grade: 4.0,
		condition_report: "Good",
		damage_notes: [],
		title_status: "clean",
		province: "Ontario",
		city: "Toronto",
		auction_start: new Date().toISOString(),
		starting_bid: 10000,
		reserve_price: null,
		buy_now_price: null,
		images: [],
		selling_dealership: "Dealer",
		lot: "A-0001",
		current_bid: null,
		bid_count: 0,
		...overrides,
	};
}

describe("ConditionSummary", () => {
	it("renders the summary text when condition_summary is set", () => {
		render(
			<ConditionSummary
				vehicle={makeVehicle({ condition_summary: SAMPLE_SUMMARY })}
			/>,
		);
		expect(screen.getByText(SAMPLE_SUMMARY)).toBeInTheDocument();
	});

	it("returns null when condition_summary is undefined", () => {
		render(<ConditionSummary vehicle={makeVehicle()} />);
		expect(
			screen.queryByRole("heading", { name: /condition summary/i }),
		).not.toBeInTheDocument();
	});

	it("returns null when condition_summary is whitespace-only", () => {
		render(
			<ConditionSummary vehicle={makeVehicle({ condition_summary: "   " })} />,
		);
		expect(
			screen.queryByRole("heading", { name: /condition summary/i }),
		).not.toBeInTheDocument();
	});

	it("renders the Claude attribution", () => {
		render(
			<ConditionSummary
				vehicle={makeVehicle({ condition_summary: SAMPLE_SUMMARY })}
			/>,
		);
		expect(screen.getByText(/Generated by Claude Haiku/)).toBeInTheDocument();
	});

	it("renders a CarFax link with correct attributes", () => {
		render(
			<ConditionSummary
				vehicle={makeVehicle({ condition_summary: SAMPLE_SUMMARY })}
			/>,
		);
		const link = screen.getByRole("link", {
			name: /Check market value on CarFax Canada/i,
		});
		expect(link).toHaveAttribute(
			"href",
			"https://www.carfax.ca/whats-my-car-worth/car-value",
		);
		expect(link).toHaveAttribute("target", "_blank");
		expect(link).toHaveAttribute("rel", "noopener noreferrer");
		const ariaLabel = link.getAttribute("aria-label");
		expect(ariaLabel).toContain("opens in new tab");
	});
});
