import { ExternalLink } from "lucide-react";
import type { Vehicle } from "../types";

const CARFAX_VALUE_URL = "https://www.carfax.ca/whats-my-car-worth/car-value";

type ConditionSummaryProps = {
	vehicle: Vehicle;
};

export function ConditionSummary({ vehicle }: ConditionSummaryProps) {
	const summary = vehicle.condition_summary?.trim();
	if (!summary) return null;

	return (
		<aside
			aria-labelledby="condition-summary-heading"
			className="rounded-2xl border border-accent/20 bg-gradient-to-br from-accent/5 to-accent-to/5 p-6"
		>
			<h2
				id="condition-summary-heading"
				className="text-sm font-semibold uppercase tracking-wider text-text-primary"
			>
				Condition Summary
			</h2>
			<p className="mt-3 text-sm leading-relaxed text-text-secondary">
				{summary}
			</p>
			<div className="mt-4 border-t border-border pt-4">
				<p className="text-xs italic text-text-muted">
					Generated by Claude Haiku · pre-computed at build time
				</p>
				<a
					href={CARFAX_VALUE_URL}
					target="_blank"
					rel="noopener noreferrer"
					aria-label="Check market value on CarFax Canada (opens in new tab)"
					className="mt-3 inline-flex items-center gap-1.5 text-sm font-medium text-accent hover:text-accent-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 focus-visible:ring-offset-page"
				>
					Check market value on CarFax Canada
					<ExternalLink className="size-3.5" aria-hidden="true" />
				</a>
			</div>
		</aside>
	);
}
